version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.34
    container_name: tmp_rails_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - tmp_db-data:/var/lib/mysql
  redis:
    platform: linux/x86_64
    image: redis:6.0-alpine
    ports:
      - 6389:6379
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  app:
    build: .
    command: > 
      bash -c "rm -f tmp/pids/* && 
      rm -f log/development.log &&
      bundle install &&
      sleep 5 &&
      rails db:create &&
      rake ridgepole:apply && 
      rake assets:precompile &&
      bundle exec puma -C config/puma.rb"
    volumes:
      - .:/tmp_rails
      - public-data:/tmp_rails/public
      - tmp-data:/tmp_rails/tmp
      - log-data:/tmp_rails/log
    environment:
      RAILS_ENV: staging
      RAILS_LOG_TO_STDOUT: staging
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  web:
    build:
      context: nginx
    volumes:
      - public-data:/tmp_rails/public
      - tmp-data:/tmp_rails/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  tmp_db-data:
  public-data:
  tmp-data:
  log-data:

